version: '3.1'

services:
  singlelink:
    ports:
      - 3000:3000
    image: jimbisenius/singlelink:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.singlelink.rule=Host(`linkinbio.boxingoctopus.io`)
      - traefik.http.routers.singlelink.tls=true
      - traefik.http.routers.singlelink.entrypoints=websecure
      - traefik.http.routers.singlelink.service=singlelink
      - traefik.http.routers.singlelink.tls.certresolver=leresolver
      - traefik.http.services.singlelink.loadbalancer.server.port=3000
      - traefik.http.middlewares.singlelink.headers.SSLRedirect=true
      - traefik.http.middlewares.singlelink.headers.STSSeconds=315360000
      - traefik.http.middlewares.singlelink.headers.browserXSSFilter=true
      - traefik.http.middlewares.singlelink.headers.contentTypeNosniff=true
      - traefik.http.middlewares.singlelink.headers.forceSTSHeader=true
      - traefik.http.middlewares.singlelink.headers.SSLHost=boxingoctopus.io
      - traefik.http.middlewares.singlelink.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.singlelink.headers.STSPreload=true
    environment:
      DB_HOST: $DB_HOSTNAME
      DB_PORT: $DB_PORT_NUMBER
      DB_DATABASE: $DB_NAME
      DB_USER: $DB_USERNAME
      DB_PASS: $DB_PASSWORD
      META_TITLE: Singlelink
      META_DESC: Boxing Octopus Creative Bio Links
      META_IMG:
      BRANDING: "true"
      SECRET: $JWT_SECRET
      PASSWORD: $PASS
      
networks:
  default:
    external: true
    name: portainer_default